
package com.allianz.pricingdetailsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.allianz.pricingdetailsservice.datamodel.ObjectFactory;
import com.allianz.pricingdetailsservice.datamodel.PricingInputType;
import com.allianz.pricingdetailsservice.datamodel.PricingOutputType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PricingDetails", targetNamespace = "http://www.allianz.com/PricingDetailsService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PricingDetails {


    /**
     * 
     * @param input
     * @return
     *     returns com.allianz.pricingdetailsservice.datamodel.PricingOutputType
     */
    @WebMethod(action = "http://www.allianz.com/PricingDetailsService/getPricing")
    @WebResult(name = "pricing-output", targetNamespace = "http://www.allianz.com/PricingDetailsService/datamodel", partName = "output")
    public PricingOutputType getPricing(
        @WebParam(name = "pricing-input", targetNamespace = "http://www.allianz.com/PricingDetailsService/datamodel", partName = "input")
        PricingInputType input);

}
